### ISSUE TITLE
Make tinted glass for underground biomes

### ISSUE THREAD

**Issue by GlowSand** [FarLanderCraft/Biospheres#1]
👍

**Comment by FarLanderCraft** [comment]
In the latest commit. :+1: 
![2021-08-12_09 09 56](https://user-images.githubusercontent.com/67613281/129202573-765557fd-3a53-49c1-8948-7a076a6badb8.png)
![2021-08-12_09 10 07](https://user-images.githubusercontent.com/67613281/129202595-32fbcc7d-a0c3-4d81-acdf-17edfa567bd3.png)
